### ISSUE TITLE
For some suggestions

### ISSUE THREAD

**Issue by jevi061** [Leboudin/DocxFactory_Archive#1]
e....I just dont know how to communicate with you in github ,so this is the reason why you now see a  issue here,,,,,,,I used Docxfactory to generate a doc file with only a table ,and I have set some fields in that table according to doc of DocxFactory,but my field didnt 
fill in that table as i want ,please ,leave some suggestions if you can,I just dont know whats wrong with it ,thanks for advance,and you cad write Chinese to me .....

**Comment by vaddenz** [comment]
你可以发一下你的 docx 模板和代码我看看 leboudin@163.com

**Comment by jevi061** [comment]
不好意思周末休息了，明天早上发你，谢谢啦

**Comment by jevi061** [comment]
[micro.docx](https://github.com/Leboudin/DocxFactory_Archive/files/2300885/micro.docx)
@Leboudin 这是文档模板和代码
`#include "docexport.h"
#include "WordProcessingMerger.h"
#include <iostream>
using namespace DocxFactory;
docexport::docexport(QWidget *parent)
	: QWidget(parent)
{
	ui.setupUi(this);
	try
	{
		WordProcessingMerger& merger = WordProcessingMerger::getInstance();
		merger.load("micro.dfw");
		merger.setCodePage("utf-8");
		merger.setClipboardValue("Line", "caseName", "heheheheheh");
		merger.setClipboardValue("Line", "casePlace", "american");
		merger.setClipboardValue("Line2", "caseDate", "2018-8-18");
		merger.setClipboardValue("Line2", "caseCompany", "google");
		merger.setClipboardValue("Line3", "caseDetail", "000000000000000000000");
		merger.paste("caseReport");
		merger.paste("Line");
		merger.paste("Line2");
		merger.paste("Line3");
		merger.save("test40.docx");
	}
	catch (const exception& p_exception)
	{
		std::cout << p_exception.what();
	}
	
}
`

**Comment by vaddenz** [comment]
已经收到模板, 我猜测是模板文件的原因, 识别不到书签和字段, 试试我这个.

我是用 WPS/WORD 新建了一份空白文档, 如果你是从 doc 文件复制的话, 猜测可能会有问题.



在 2018-08-20 09:14:19，"Jevi06" <notifications@github.com> 写道：


micro.docx
@Leboudin 这是文档模板和代码
`#include "docexport.h"
#include "WordProcessingMerger.h"
#include
using namespace DocxFactory;
docexport::docexport(QWidget *parent)
: QWidget(parent)
{
ui.setupUi(this);
try
{
WordProcessingMerger& merger = WordProcessingMerger::getInstance();
merger.load("micro.dfw");
merger.setCodePage("utf-8");
merger.setClipboardValue("Line", "caseName", "heheheheheh");
merger.setClipboardValue("Line", "casePlace", "american");
merger.setClipboardValue("Line2", "caseDate", "2018-8-18");
merger.setClipboardValue("Line2", "caseCompany", "google");
merger.setClipboardValue("Line3", "caseDetail", "000000000000000000000");
merger.paste("caseReport");
merger.paste("Line");
merger.paste("Line2");
merger.paste("Line3");
merger.save("test40.docx");
}
catch (const exception& p_exception)
{
std::cout << p_exception.what();
}

}
`

**Comment by vaddenz** [comment]
我在 issue里上传不了文件, 你可以看下仓库里的 origin/master/Header.docx 



https://github.com/Leboudin/DocxFactory_Archive/blob/master/Header.docx?raw=true



在 2018-08-20 09:14:19，"Jevi06" <notifications@github.com> 写道：


micro.docx
@Leboudin 这是文档模板和代码
`#include "docexport.h"
#include "WordProcessingMerger.h"
#include
using namespace DocxFactory;
docexport::docexport(QWidget *parent)
: QWidget(parent)
{
ui.setupUi(this);
try
{
WordProcessingMerger& merger = WordProcessingMerger::getInstance();
merger.load("micro.dfw");
merger.setCodePage("utf-8");
merger.setClipboardValue("Line", "caseName", "heheheheheh");
merger.setClipboardValue("Line", "casePlace", "american");
merger.setClipboardValue("Line2", "caseDate", "2018-8-18");
merger.setClipboardValue("Line2", "caseCompany", "google");
merger.setClipboardValue("Line3", "caseDetail", "000000000000000000000");
merger.paste("caseReport");
merger.paste("Line");
merger.paste("Line2");
merger.paste("Line3");
merger.save("test40.docx");
}
catch (const exception& p_exception)
{
std::cout << p_exception.what();
}

}
`

**Comment by jevi061** [comment]
issue输入框蓝色虚线下方有attch file的选项，我按照你的模板生成，结果也不符合预想的结果，你可以看下，我的代码和生成结果：`try
	{
		WordProcessingMerger& merger = WordProcessingMerger::getInstance();
		merger.load("Header.dfw");
		merger.setClipboardValue("row1", "caseName", "heheheheheh");
		merger.setClipboardValue("row1", "casePlace", "american");
		merger.setClipboardValue("row2", "caseDate", "2018-8-18");
		merger.setClipboardValue("row2", "caseCompany", "google");
		merger.setClipboardValue("row3", "caseDetail", "000000000000000000000");
		merger.paste("Hader");
		 merger.paste("row1");
		 merger.paste("row2");
		merger.paste("row3");
		merger.save("gihub.docx");
	}
	catch (const exception& p_exception)
	{
		std::cout << p_exception.what();
	}
[gihub.docx](https://github.com/Leboudin/DocxFactory_Archive/files/2301107/gihub.docx)
`

**Comment by jevi061** [comment]
`try
	{
		WordProcessingMerger& merger = WordProcessingMerger::getInstance();
		merger.load("Header.dfw");
		merger.setClipboardValue("row1", "caseName", "heheheheheh");
		merger.setClipboardValue("row1", "casePlace", "american");
		merger.setClipboardValue("row2", "caseDate", "2018-8-18");
		merger.setClipboardValue("row2", "caseCompany", "google");
		merger.setClipboardValue("row3", "caseDetail", "000000000000000000000");
		merger.paste("Hader");
		 merger.paste("row1");
		 merger.paste("row2");
		merger.paste("row3");
		merger.save("gihub.docx");
	}
	catch (const exception& p_exception)
	{
		std::cout << p_exception.what();
	}`

**Comment by jevi061** [comment]
好像代码格式化效果不好
![default](https://user-images.githubusercontent.com/17949749/44320182-e4674400-a472-11e8-9134-d270c1ca5bd9.png)

**Comment by jevi061** [comment]
我之前的确是从docx文件里复制了一个表格出来测试的，但是刚新建的表格也是得不到想要的结果，
![result](https://user-images.githubusercontent.com/17949749/44324179-56498880-a487-11e8-9dbb-bdb023f14d86.png)
只是少了一个左括号。我用的是word2016

**Comment by jevi061** [comment]
是我代码写的有问题，每setClipboardValue一个item,就需要先paste它然后再处理别的item否则，会覆盖之前设置过的值，，，，，，，，
